name: Workflow Execution
on:
    workflow_dispatch:
        inputs:
            result:
                description: 'Debe funcionar correctamente?'
                type: choice
                options:
                    - SI
                    - NO
                default: SI
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build_status: ${{ steps.build.outputs.variable }}
        steps:
            - name: 'Print GITHUB_OUTPUT path'
              run: |
                echo "var -->> $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "Building"
                echo "variable=${{inputs.result}}" >> "$GITHUB_OUTPUT"
  
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build_status == 'SI' }}
        steps:
            - name: Deploy
              run: |
                echo "Deploying"
    rollback:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build_status == 'NO' }}
        steps:
            - name: Rollback
              run: |
                echo "Rollback"
                exit 1
